env:
  node: true
  commonjs: true
  es6: true
  browser: true
extends:
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
